// Re-export all types from slices for backwards compatibility.
// Extracted from store.ts to keep that file under the max-lines limit.
import type { SessionRuntimeSlice, SessionSliceActions } from "./slices";

export type WorkspaceSourceStoreState = Pick<
  SessionRuntimeSlice,
  "workspaceFilesRefresh" | "bumpWorkspaceFilesRefresh"
> &
  Pick<SessionSliceActions, "reconcileWorkspaceSourcesAdopted">;

export type {
  KanbanState,
  KanbanMultiState,
  WorkflowSnapshotData,
  WorkflowsState,
  TaskState,
  WorkspaceState,
  RepositoriesState,
  RepositoryBranchesState,
  RepositoryScriptsState,
  ExecutorsState,
  SettingsAgentsState,
  AgentDiscoveryState,
  AvailableAgentsState,
  AgentProfileOption,
  AgentProfilesState,
  EditorsState,
  PromptsState,
  SecretsState,
  NotificationProvidersState,
  SettingsDataState,
  SleepInhibitionStoreState,
  UserSettingsState,
  AgentProfileRecentUseState,
  AgentProfileRecentUseRecord,
  MessagesState,
  TurnsState,
  TaskSessionsState,
  TaskSessionsByTaskState,
  SessionAgentctlStatus,
  SessionAgentctlState,
  Worktree,
  WorktreesState,
  SessionWorktreesState,
  PendingModelState,
  ActiveModelState,
  TerminalState,
  ShellState,
  ProcessStatusEntry,
  ProcessState,
  FileInfo,
  GitStatusEntry,
  GitStatusState,
  ContextWindowEntry,
  ContextWindowState,
  AgentState,
  UserShellInfo,
  UserShellsState,
  PreviewStage,
  PreviewViewMode,
  PreviewDevicePreset,
  PreviewPanelState,
  RightPanelState,
  DiffState,
  ConnectionState,
  MobileKanbanState,
  GitHubSlice,
  GitHubSliceState,
  GitHubSliceActions,
  GitHubStatusState,
  GitHubAppRegistrationsState,
  TaskPRsState,
  PRWatchesState,
  ReviewWatchesState,
  IssueWatchesState,
  JiraSlice,
  JiraSliceState,
  JiraSliceActions,
  JiraIssueWatchesState,
  LinearSlice,
  LinearSliceState,
  LinearSliceActions,
  LinearIssueWatchesState,
  AzureDevOpsSlice,
  AzureDevOpsSliceState,
  AzureDevOpsSliceActions,
  AzureDevOpsTaskPullRequestsState,
} from "./slices";
