// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: kandev/plugin/v1/plugin.proto

package pluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Plugin_DeliverEvent_FullMethodName             = "/kandev.plugin.v1.Plugin/DeliverEvent"
	Plugin_HandleWebhook_FullMethodName            = "/kandev.plugin.v1.Plugin/HandleWebhook"
	Plugin_HandleAction_FullMethodName             = "/kandev.plugin.v1.Plugin/HandleAction"
	Plugin_SearchEntityReferences_FullMethodName   = "/kandev.plugin.v1.Plugin/SearchEntityReferences"
	Plugin_AuthorizeEntityReference_FullMethodName = "/kandev.plugin.v1.Plugin/AuthorizeEntityReference"
	Plugin_ResolveGitCredential_FullMethodName     = "/kandev.plugin.v1.Plugin/ResolveGitCredential"
	Plugin_GetGitCredentialBinding_FullMethodName  = "/kandev.plugin.v1.Plugin/GetGitCredentialBinding"
	Plugin_InvokeAgentTool_FullMethodName          = "/kandev.plugin.v1.Plugin/InvokeAgentTool"
)

// PluginClient is the client API for Plugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Implemented by the PLUGIN. kandev is the client.
type PluginClient interface {
	DeliverEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*EventAck, error)
	HandleWebhook(ctx context.Context, in *WebhookRequest, opts ...grpc.CallOption) (*WebhookResponse, error)
	// Browser-originated calls reach this method only through Kandev's
	// authenticated declared-action route. Context is host-verified; body is
	// bounded untrusted JSON.
	HandleAction(ctx context.Context, in *PluginActionRequest, opts ...grpc.CallOption) (*PluginActionResponse, error)
	// Dynamic composer-reference operations. Candidate identity is untrusted;
	// the host owns canonical references and reauthorizes on submission.
	SearchEntityReferences(ctx context.Context, in *SearchEntityReferencesRequest, opts ...grpc.CallOption) (*SearchEntityReferencesResponse, error)
	AuthorizeEntityReference(ctx context.Context, in *AuthorizeEntityReferenceRequest, opts ...grpc.CallOption) (*AuthorizeEntityReferenceResponse, error)
	// Optional resolver for manifest-owned repository providers. Returned
	// credentials are transient and never persisted by the host.
	ResolveGitCredential(ctx context.Context, in *ResolveGitCredentialRequest, opts ...grpc.CallOption) (*ResolveGitCredentialResponse, error)
	// Optional non-secret credential revision for an exact resolver scope.
	// The host stores this opaque value in a lease and compares it before and
	// after credential redemption so a rotated or disconnected provider fails
	// closed without resolving a secret merely to inspect its revision.
	GetGitCredentialBinding(ctx context.Context, in *GitCredentialBindingRequest, opts ...grpc.CallOption) (*GitCredentialBindingResponse, error)
	InvokeAgentTool(ctx context.Context, in *AgentToolRequest, opts ...grpc.CallOption) (*AgentToolResponse, error)
}

type pluginClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginClient(cc grpc.ClientConnInterface) PluginClient {
	return &pluginClient{cc}
}

func (c *pluginClient) DeliverEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*EventAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventAck)
	err := c.cc.Invoke(ctx, Plugin_DeliverEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) HandleWebhook(ctx context.Context, in *WebhookRequest, opts ...grpc.CallOption) (*WebhookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WebhookResponse)
	err := c.cc.Invoke(ctx, Plugin_HandleWebhook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) HandleAction(ctx context.Context, in *PluginActionRequest, opts ...grpc.CallOption) (*PluginActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PluginActionResponse)
	err := c.cc.Invoke(ctx, Plugin_HandleAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) SearchEntityReferences(ctx context.Context, in *SearchEntityReferencesRequest, opts ...grpc.CallOption) (*SearchEntityReferencesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchEntityReferencesResponse)
	err := c.cc.Invoke(ctx, Plugin_SearchEntityReferences_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) AuthorizeEntityReference(ctx context.Context, in *AuthorizeEntityReferenceRequest, opts ...grpc.CallOption) (*AuthorizeEntityReferenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthorizeEntityReferenceResponse)
	err := c.cc.Invoke(ctx, Plugin_AuthorizeEntityReference_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) ResolveGitCredential(ctx context.Context, in *ResolveGitCredentialRequest, opts ...grpc.CallOption) (*ResolveGitCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveGitCredentialResponse)
	err := c.cc.Invoke(ctx, Plugin_ResolveGitCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) GetGitCredentialBinding(ctx context.Context, in *GitCredentialBindingRequest, opts ...grpc.CallOption) (*GitCredentialBindingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GitCredentialBindingResponse)
	err := c.cc.Invoke(ctx, Plugin_GetGitCredentialBinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) InvokeAgentTool(ctx context.Context, in *AgentToolRequest, opts ...grpc.CallOption) (*AgentToolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentToolResponse)
	err := c.cc.Invoke(ctx, Plugin_InvokeAgentTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginServer is the server API for Plugin service.
// All implementations must embed UnimplementedPluginServer
// for forward compatibility.
//
// Implemented by the PLUGIN. kandev is the client.
type PluginServer interface {
	DeliverEvent(context.Context, *Event) (*EventAck, error)
	HandleWebhook(context.Context, *WebhookRequest) (*WebhookResponse, error)
	// Browser-originated calls reach this method only through Kandev's
	// authenticated declared-action route. Context is host-verified; body is
	// bounded untrusted JSON.
	HandleAction(context.Context, *PluginActionRequest) (*PluginActionResponse, error)
	// Dynamic composer-reference operations. Candidate identity is untrusted;
	// the host owns canonical references and reauthorizes on submission.
	SearchEntityReferences(context.Context, *SearchEntityReferencesRequest) (*SearchEntityReferencesResponse, error)
	AuthorizeEntityReference(context.Context, *AuthorizeEntityReferenceRequest) (*AuthorizeEntityReferenceResponse, error)
	// Optional resolver for manifest-owned repository providers. Returned
	// credentials are transient and never persisted by the host.
	ResolveGitCredential(context.Context, *ResolveGitCredentialRequest) (*ResolveGitCredentialResponse, error)
	// Optional non-secret credential revision for an exact resolver scope.
	// The host stores this opaque value in a lease and compares it before and
	// after credential redemption so a rotated or disconnected provider fails
	// closed without resolving a secret merely to inspect its revision.
	GetGitCredentialBinding(context.Context, *GitCredentialBindingRequest) (*GitCredentialBindingResponse, error)
	InvokeAgentTool(context.Context, *AgentToolRequest) (*AgentToolResponse, error)
	mustEmbedUnimplementedPluginServer()
}

// UnimplementedPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginServer struct{}

func (UnimplementedPluginServer) DeliverEvent(context.Context, *Event) (*EventAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeliverEvent not implemented")
}
func (UnimplementedPluginServer) HandleWebhook(context.Context, *WebhookRequest) (*WebhookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleWebhook not implemented")
}
func (UnimplementedPluginServer) HandleAction(context.Context, *PluginActionRequest) (*PluginActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleAction not implemented")
}
func (UnimplementedPluginServer) SearchEntityReferences(context.Context, *SearchEntityReferencesRequest) (*SearchEntityReferencesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchEntityReferences not implemented")
}
func (UnimplementedPluginServer) AuthorizeEntityReference(context.Context, *AuthorizeEntityReferenceRequest) (*AuthorizeEntityReferenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthorizeEntityReference not implemented")
}
func (UnimplementedPluginServer) ResolveGitCredential(context.Context, *ResolveGitCredentialRequest) (*ResolveGitCredentialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveGitCredential not implemented")
}
func (UnimplementedPluginServer) GetGitCredentialBinding(context.Context, *GitCredentialBindingRequest) (*GitCredentialBindingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGitCredentialBinding not implemented")
}
func (UnimplementedPluginServer) InvokeAgentTool(context.Context, *AgentToolRequest) (*AgentToolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InvokeAgentTool not implemented")
}
func (UnimplementedPluginServer) mustEmbedUnimplementedPluginServer() {}
func (UnimplementedPluginServer) testEmbeddedByValue()                {}

// UnsafePluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginServer will
// result in compilation errors.
type UnsafePluginServer interface {
	mustEmbedUnimplementedPluginServer()
}

func RegisterPluginServer(s grpc.ServiceRegistrar, srv PluginServer) {
	// If the following call pancis, it indicates UnimplementedPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Plugin_ServiceDesc, srv)
}

func _Plugin_DeliverEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).DeliverEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_DeliverEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).DeliverEvent(ctx, req.(*Event))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_HandleWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).HandleWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_HandleWebhook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).HandleWebhook(ctx, req.(*WebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_HandleAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).HandleAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_HandleAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).HandleAction(ctx, req.(*PluginActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_SearchEntityReferences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchEntityReferencesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).SearchEntityReferences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_SearchEntityReferences_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).SearchEntityReferences(ctx, req.(*SearchEntityReferencesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_AuthorizeEntityReference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizeEntityReferenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).AuthorizeEntityReference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_AuthorizeEntityReference_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).AuthorizeEntityReference(ctx, req.(*AuthorizeEntityReferenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_ResolveGitCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveGitCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).ResolveGitCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_ResolveGitCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).ResolveGitCredential(ctx, req.(*ResolveGitCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_GetGitCredentialBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GitCredentialBindingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).GetGitCredentialBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_GetGitCredentialBinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).GetGitCredentialBinding(ctx, req.(*GitCredentialBindingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_InvokeAgentTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).InvokeAgentTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_InvokeAgentTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).InvokeAgentTool(ctx, req.(*AgentToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Plugin_ServiceDesc is the grpc.ServiceDesc for Plugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Plugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kandev.plugin.v1.Plugin",
	HandlerType: (*PluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeliverEvent",
			Handler:    _Plugin_DeliverEvent_Handler,
		},
		{
			MethodName: "HandleWebhook",
			Handler:    _Plugin_HandleWebhook_Handler,
		},
		{
			MethodName: "HandleAction",
			Handler:    _Plugin_HandleAction_Handler,
		},
		{
			MethodName: "SearchEntityReferences",
			Handler:    _Plugin_SearchEntityReferences_Handler,
		},
		{
			MethodName: "AuthorizeEntityReference",
			Handler:    _Plugin_AuthorizeEntityReference_Handler,
		},
		{
			MethodName: "ResolveGitCredential",
			Handler:    _Plugin_ResolveGitCredential_Handler,
		},
		{
			MethodName: "GetGitCredentialBinding",
			Handler:    _Plugin_GetGitCredentialBinding_Handler,
		},
		{
			MethodName: "InvokeAgentTool",
			Handler:    _Plugin_InvokeAgentTool_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kandev/plugin/v1/plugin.proto",
}

const (
	Host_GetState_FullMethodName                   = "/kandev.plugin.v1.Host/GetState"
	Host_SetState_FullMethodName                   = "/kandev.plugin.v1.Host/SetState"
	Host_DeleteState_FullMethodName                = "/kandev.plugin.v1.Host/DeleteState"
	Host_ListState_FullMethodName                  = "/kandev.plugin.v1.Host/ListState"
	Host_RevealSecret_FullMethodName               = "/kandev.plugin.v1.Host/RevealSecret"
	Host_EmitEvent_FullMethodName                  = "/kandev.plugin.v1.Host/EmitEvent"
	Host_GetSecret_FullMethodName                  = "/kandev.plugin.v1.Host/GetSecret"
	Host_SetSecret_FullMethodName                  = "/kandev.plugin.v1.Host/SetSecret"
	Host_DeleteSecret_FullMethodName               = "/kandev.plugin.v1.Host/DeleteSecret"
	Host_GetConfig_FullMethodName                  = "/kandev.plugin.v1.Host/GetConfig"
	Host_ListTasks_FullMethodName                  = "/kandev.plugin.v1.Host/ListTasks"
	Host_GetTask_FullMethodName                    = "/kandev.plugin.v1.Host/GetTask"
	Host_ListWorkspaces_FullMethodName             = "/kandev.plugin.v1.Host/ListWorkspaces"
	Host_ListWorkflows_FullMethodName              = "/kandev.plugin.v1.Host/ListWorkflows"
	Host_ListWorkflowSteps_FullMethodName          = "/kandev.plugin.v1.Host/ListWorkflowSteps"
	Host_ListAgentProfiles_FullMethodName          = "/kandev.plugin.v1.Host/ListAgentProfiles"
	Host_ListExecutorProfiles_FullMethodName       = "/kandev.plugin.v1.Host/ListExecutorProfiles"
	Host_ListRepositories_FullMethodName           = "/kandev.plugin.v1.Host/ListRepositories"
	Host_ListSessions_FullMethodName               = "/kandev.plugin.v1.Host/ListSessions"
	Host_ListSessionCodeStats_FullMethodName       = "/kandev.plugin.v1.Host/ListSessionCodeStats"
	Host_ListMessages_FullMethodName               = "/kandev.plugin.v1.Host/ListMessages"
	Host_ListPendingInteractions_FullMethodName    = "/kandev.plugin.v1.Host/ListPendingInteractions"
	Host_GetInteraction_FullMethodName             = "/kandev.plugin.v1.Host/GetInteraction"
	Host_InvokeUtilityAgent_FullMethodName         = "/kandev.plugin.v1.Host/InvokeUtilityAgent"
	Host_CreateTask_FullMethodName                 = "/kandev.plugin.v1.Host/CreateTask"
	Host_UpdateTask_FullMethodName                 = "/kandev.plugin.v1.Host/UpdateTask"
	Host_MoveTask_FullMethodName                   = "/kandev.plugin.v1.Host/MoveTask"
	Host_SendMessage_FullMethodName                = "/kandev.plugin.v1.Host/SendMessage"
	Host_PreviewPluginOwnedTaskTree_FullMethodName = "/kandev.plugin.v1.Host/PreviewPluginOwnedTaskTree"
	Host_DeletePluginOwnedTaskTree_FullMethodName  = "/kandev.plugin.v1.Host/DeletePluginOwnedTaskTree"
	Host_RespondToPermission_FullMethodName        = "/kandev.plugin.v1.Host/RespondToPermission"
	Host_AnswerClarification_FullMethodName        = "/kandev.plugin.v1.Host/AnswerClarification"
	Host_CancelClarification_FullMethodName        = "/kandev.plugin.v1.Host/CancelClarification"
)

// HostClient is the client API for Host service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Implemented by KANDEV (served back over the go-plugin broker).
// Reads (§5) and writes are capability-gated server-side by an inline
// per-resource check at the start of each handler — there is no unary
// interceptor enforcing this centrally.
//
// Host data API (ADR 0043): the read/write data RPCs below live on this same
// `service Host` rather than a separate `service HostData`. They reuse the
// single broker connection; splitting into a second service would only
// duplicate that for no benefit. Reads require manifest capability
// `api_read:<resource>`; writes require `api_write:<resource>` (e.g.
// `api_read:tasks`, `api_write:comments`). An undeclared capability returns
// gRPC PermissionDenied with `capability 'api_read:tasks' not declared` (or
// `api_write:tasks`, etc.).
//
// DTOs below are a HAND-DEFINED public contract: the backend maps internal
// models → these messages explicitly, never generates them from domain
// structs, and never marshals domain structs through google.protobuf.Struct.
// Fields are additive-only after merge (ADR 0043); removing or renaming a
// field is a breaking change requiring a new api_version. Read handlers call
// the relevant service (never a repository directly); write handlers call
// service methods that publish task.* events (never repository.TaskRepository).
type HostClient interface {
	GetState(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*GetStateResponse, error)
	SetState(ctx context.Context, in *SetStateRequest, opts ...grpc.CallOption) (*SetStateResponse, error)
	DeleteState(ctx context.Context, in *DeleteStateRequest, opts ...grpc.CallOption) (*DeleteStateResponse, error)
	ListState(ctx context.Context, in *ListStateRequest, opts ...grpc.CallOption) (*ListStateResponse, error)
	RevealSecret(ctx context.Context, in *RevealSecretRequest, opts ...grpc.CallOption) (*RevealSecretResponse, error)
	EmitEvent(ctx context.Context, in *EmitEventRequest, opts ...grpc.CallOption) (*EmitEventResponse, error)
	// Plugin-scoped secret primitives — capability `secrets`, like
	// RevealSecret. Keys are namespaced server-side to the calling plugin
	// (vault id "plugin:<id>:secret:<key>"), so a plugin can only ever read,
	// write, or delete its OWN secrets; RevealSecret remains the way to
	// resolve an operator-provided reference to a shared/global secret.
	// Values are stored in kandev's encrypted secret vault (AES-256-GCM at
	// rest), never on the plugin record or config file.
	GetSecret(ctx context.Context, in *GetSecretRequest, opts ...grpc.CallOption) (*GetSecretResponse, error)
	SetSecret(ctx context.Context, in *SetSecretRequest, opts ...grpc.CallOption) (*SetSecretResponse, error)
	DeleteSecret(ctx context.Context, in *DeleteSecretRequest, opts ...grpc.CallOption) (*DeleteSecretResponse, error)
	// GetConfig returns the plugin's own operator-editable config (the values
	// set in Settings > Plugins > <plugin> against the manifest's
	// config_schema). Ungated: a plugin can always read its own config, secret
	// values included — that is how e.g. an operator-configured PAT reaches
	// the plugin.
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error)
	// Reads — capability api_read:<resource>
	ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error)
	GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*GetTaskResponse, error)
	ListWorkspaces(ctx context.Context, in *ListWorkspacesRequest, opts ...grpc.CallOption) (*ListWorkspacesResponse, error)
	ListWorkflows(ctx context.Context, in *ListWorkflowsRequest, opts ...grpc.CallOption) (*ListWorkflowsResponse, error)
	ListWorkflowSteps(ctx context.Context, in *ListWorkflowStepsRequest, opts ...grpc.CallOption) (*ListWorkflowStepsResponse, error)
	ListAgentProfiles(ctx context.Context, in *ListAgentProfilesRequest, opts ...grpc.CallOption) (*ListAgentProfilesResponse, error)
	ListExecutorProfiles(ctx context.Context, in *ListExecutorProfilesRequest, opts ...grpc.CallOption) (*ListExecutorProfilesResponse, error)
	ListRepositories(ctx context.Context, in *ListRepositoriesRequest, opts ...grpc.CallOption) (*ListRepositoriesResponse, error)
	// Sessions + code stats — capability api_read:sessions. Driven by a real
	// plugin (kandev-plugin-agent-stats) that otherwise read task_sessions,
	// task_session_commits, and task_session_git_snapshots straight from the
	// SQLite file. SessionCodeStats is a COMPUTED, stable DTO — deliberately
	// not the raw commit/snapshot rows, whose JSON schema churns.
	ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error)
	ListSessionCodeStats(ctx context.Context, in *ListSessionCodeStatsRequest, opts ...grpc.CallOption) (*ListSessionCodeStatsResponse, error)
	// Conversation content — capability api_read:messages. Historical
	// user/agent message content for a session or task, filterable by a time
	// range (e.g. "yesterday"). Content is sanitized: kandev-injected
	// <kandev-system> blocks are stripped, exactly like the message.added bus
	// event — raw system prompts are never exposed to plugins.
	ListMessages(ctx context.Context, in *ListMessagesRequest, opts ...grpc.CallOption) (*ListMessagesResponse, error)
	// Pending agent interactions — capability api_read:interactions. The
	// DURABLE record of every permission request and clarification bundle still
	// owed a human response, under the same turn/session authority kandev's own
	// list surfaces use. Session state alone cannot answer this: WAITING_FOR_INPUT
	// also describes an ordinarily completed turn, so a state-only consumer
	// reports attention that is not owed. Reading the record is what lets a
	// consumer that started late, restarted, or missed an event reconcile.
	// GetInteraction resolves ANY interaction — including terminal ones — so a
	// replayed or missed event converges on the current result instead of
	// NotFound.
	ListPendingInteractions(ctx context.Context, in *ListPendingInteractionsRequest, opts ...grpc.CallOption) (*ListPendingInteractionsResponse, error)
	GetInteraction(ctx context.Context, in *GetInteractionRequest, opts ...grpc.CallOption) (*GetInteractionResponse, error)
	// Utility agent — capability agent_invoke. Runs a one-shot, non-interactive
	// completion using the operator-configured "utility agent" profile (Settings
	// > System), so a plugin can delegate a lightweight LLM step without holding
	// its own API key. FailedPrecondition when no utility agent is configured.
	InvokeUtilityAgent(ctx context.Context, in *InvokeUtilityAgentRequest, opts ...grpc.CallOption) (*InvokeUtilityAgentResponse, error)
	// Writes — capability api_write:<resource>. Route through the first-party
	// service layer so events fire and WS clients update — the whole reason not
	// to let plugins write the DB. CreateTask/UpdateTask require api_write:tasks
	// and go through the task service (task.* events; kandev stamps
	// source = "plugin:<id>" on created rows, a plugin cannot set it). SendMessage
	// requires api_write:messages and delivers a prompt to a task session through
	// the orchestrator — the same delivery path message_task uses (queue when the
	// session is running, resume/start it otherwise).
	CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*CreateTaskResponse, error)
	UpdateTask(ctx context.Context, in *UpdateTaskRequest, opts ...grpc.CallOption) (*UpdateTaskResponse, error)
	// MoveTask transitions a task to a workflow step through the same path the
	// board's own move uses (validation, WIP admission, task.moved publication,
	// auto-start gates, queue reconciliation) — unlike UpdateTask, which rejects
	// workflow_step_id. Requires api_write:tasks.
	MoveTask(ctx context.Context, in *MoveTaskRequest, opts ...grpc.CallOption) (*MoveTaskResponse, error)
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error)
	PreviewPluginOwnedTaskTree(ctx context.Context, in *PreviewPluginOwnedTaskTreeRequest, opts ...grpc.CallOption) (*PreviewPluginOwnedTaskTreeResponse, error)
	DeletePluginOwnedTaskTree(ctx context.Context, in *DeletePluginOwnedTaskTreeRequest, opts ...grpc.CallOption) (*DeletePluginOwnedTaskTreeResponse, error)
	// Interaction responses — capability api_write:interactions. Each routes
	// through the same first-party service the native UI uses, so the agent
	// unblocks, the durable record turns terminal, and every surface converges
	// through the normal events. Terminal-once: an interaction that already has
	// a resolution answers FailedPrecondition rather than dispatching a second
	// response, and an unknown id answers NotFound — the two outcomes a
	// reconciling cache needs to distinguish "someone else got there first" from
	// "I am holding a stale id".
	RespondToPermission(ctx context.Context, in *RespondToPermissionRequest, opts ...grpc.CallOption) (*RespondToPermissionResponse, error)
	AnswerClarification(ctx context.Context, in *AnswerClarificationRequest, opts ...grpc.CallOption) (*AnswerClarificationResponse, error)
	CancelClarification(ctx context.Context, in *CancelClarificationRequest, opts ...grpc.CallOption) (*CancelClarificationResponse, error)
}

type hostClient struct {
	cc grpc.ClientConnInterface
}

func NewHostClient(cc grpc.ClientConnInterface) HostClient {
	return &hostClient{cc}
}

func (c *hostClient) GetState(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*GetStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStateResponse)
	err := c.cc.Invoke(ctx, Host_GetState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) SetState(ctx context.Context, in *SetStateRequest, opts ...grpc.CallOption) (*SetStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetStateResponse)
	err := c.cc.Invoke(ctx, Host_SetState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) DeleteState(ctx context.Context, in *DeleteStateRequest, opts ...grpc.CallOption) (*DeleteStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteStateResponse)
	err := c.cc.Invoke(ctx, Host_DeleteState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) ListState(ctx context.Context, in *ListStateRequest, opts ...grpc.CallOption) (*ListStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListStateResponse)
	err := c.cc.Invoke(ctx, Host_ListState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) RevealSecret(ctx context.Context, in *RevealSecretRequest, opts ...grpc.CallOption) (*RevealSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevealSecretResponse)
	err := c.cc.Invoke(ctx, Host_RevealSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) EmitEvent(ctx context.Context, in *EmitEventRequest, opts ...grpc.CallOption) (*EmitEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmitEventResponse)
	err := c.cc.Invoke(ctx, Host_EmitEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) GetSecret(ctx context.Context, in *GetSecretRequest, opts ...grpc.CallOption) (*GetSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSecretResponse)
	err := c.cc.Invoke(ctx, Host_GetSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) SetSecret(ctx context.Context, in *SetSecretRequest, opts ...grpc.CallOption) (*SetSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetSecretResponse)
	err := c.cc.Invoke(ctx, Host_SetSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) DeleteSecret(ctx context.Context, in *DeleteSecretRequest, opts ...grpc.CallOption) (*DeleteSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSecretResponse)
	err := c.cc.Invoke(ctx, Host_DeleteSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConfigResponse)
	err := c.cc.Invoke(ctx, Host_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTasksResponse)
	err := c.cc.Invoke(ctx, Host_ListTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*GetTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskResponse)
	err := c.cc.Invoke(ctx, Host_GetTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) ListWorkspaces(ctx context.Context, in *ListWorkspacesRequest, opts ...grpc.CallOption) (*ListWorkspacesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWorkspacesResponse)
	err := c.cc.Invoke(ctx, Host_ListWorkspaces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) ListWorkflows(ctx context.Context, in *ListWorkflowsRequest, opts ...grpc.CallOption) (*ListWorkflowsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWorkflowsResponse)
	err := c.cc.Invoke(ctx, Host_ListWorkflows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) ListWorkflowSteps(ctx context.Context, in *ListWorkflowStepsRequest, opts ...grpc.CallOption) (*ListWorkflowStepsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWorkflowStepsResponse)
	err := c.cc.Invoke(ctx, Host_ListWorkflowSteps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) ListAgentProfiles(ctx context.Context, in *ListAgentProfilesRequest, opts ...grpc.CallOption) (*ListAgentProfilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAgentProfilesResponse)
	err := c.cc.Invoke(ctx, Host_ListAgentProfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) ListExecutorProfiles(ctx context.Context, in *ListExecutorProfilesRequest, opts ...grpc.CallOption) (*ListExecutorProfilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListExecutorProfilesResponse)
	err := c.cc.Invoke(ctx, Host_ListExecutorProfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) ListRepositories(ctx context.Context, in *ListRepositoriesRequest, opts ...grpc.CallOption) (*ListRepositoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRepositoriesResponse)
	err := c.cc.Invoke(ctx, Host_ListRepositories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionsResponse)
	err := c.cc.Invoke(ctx, Host_ListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) ListSessionCodeStats(ctx context.Context, in *ListSessionCodeStatsRequest, opts ...grpc.CallOption) (*ListSessionCodeStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionCodeStatsResponse)
	err := c.cc.Invoke(ctx, Host_ListSessionCodeStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) ListMessages(ctx context.Context, in *ListMessagesRequest, opts ...grpc.CallOption) (*ListMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMessagesResponse)
	err := c.cc.Invoke(ctx, Host_ListMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) ListPendingInteractions(ctx context.Context, in *ListPendingInteractionsRequest, opts ...grpc.CallOption) (*ListPendingInteractionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPendingInteractionsResponse)
	err := c.cc.Invoke(ctx, Host_ListPendingInteractions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) GetInteraction(ctx context.Context, in *GetInteractionRequest, opts ...grpc.CallOption) (*GetInteractionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInteractionResponse)
	err := c.cc.Invoke(ctx, Host_GetInteraction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) InvokeUtilityAgent(ctx context.Context, in *InvokeUtilityAgentRequest, opts ...grpc.CallOption) (*InvokeUtilityAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvokeUtilityAgentResponse)
	err := c.cc.Invoke(ctx, Host_InvokeUtilityAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*CreateTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTaskResponse)
	err := c.cc.Invoke(ctx, Host_CreateTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) UpdateTask(ctx context.Context, in *UpdateTaskRequest, opts ...grpc.CallOption) (*UpdateTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTaskResponse)
	err := c.cc.Invoke(ctx, Host_UpdateTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) MoveTask(ctx context.Context, in *MoveTaskRequest, opts ...grpc.CallOption) (*MoveTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MoveTaskResponse)
	err := c.cc.Invoke(ctx, Host_MoveTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMessageResponse)
	err := c.cc.Invoke(ctx, Host_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) PreviewPluginOwnedTaskTree(ctx context.Context, in *PreviewPluginOwnedTaskTreeRequest, opts ...grpc.CallOption) (*PreviewPluginOwnedTaskTreeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreviewPluginOwnedTaskTreeResponse)
	err := c.cc.Invoke(ctx, Host_PreviewPluginOwnedTaskTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) DeletePluginOwnedTaskTree(ctx context.Context, in *DeletePluginOwnedTaskTreeRequest, opts ...grpc.CallOption) (*DeletePluginOwnedTaskTreeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePluginOwnedTaskTreeResponse)
	err := c.cc.Invoke(ctx, Host_DeletePluginOwnedTaskTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) RespondToPermission(ctx context.Context, in *RespondToPermissionRequest, opts ...grpc.CallOption) (*RespondToPermissionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RespondToPermissionResponse)
	err := c.cc.Invoke(ctx, Host_RespondToPermission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) AnswerClarification(ctx context.Context, in *AnswerClarificationRequest, opts ...grpc.CallOption) (*AnswerClarificationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnswerClarificationResponse)
	err := c.cc.Invoke(ctx, Host_AnswerClarification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) CancelClarification(ctx context.Context, in *CancelClarificationRequest, opts ...grpc.CallOption) (*CancelClarificationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelClarificationResponse)
	err := c.cc.Invoke(ctx, Host_CancelClarification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HostServer is the server API for Host service.
// All implementations must embed UnimplementedHostServer
// for forward compatibility.
//
// Implemented by KANDEV (served back over the go-plugin broker).
// Reads (§5) and writes are capability-gated server-side by an inline
// per-resource check at the start of each handler — there is no unary
// interceptor enforcing this centrally.
//
// Host data API (ADR 0043): the read/write data RPCs below live on this same
// `service Host` rather than a separate `service HostData`. They reuse the
// single broker connection; splitting into a second service would only
// duplicate that for no benefit. Reads require manifest capability
// `api_read:<resource>`; writes require `api_write:<resource>` (e.g.
// `api_read:tasks`, `api_write:comments`). An undeclared capability returns
// gRPC PermissionDenied with `capability 'api_read:tasks' not declared` (or
// `api_write:tasks`, etc.).
//
// DTOs below are a HAND-DEFINED public contract: the backend maps internal
// models → these messages explicitly, never generates them from domain
// structs, and never marshals domain structs through google.protobuf.Struct.
// Fields are additive-only after merge (ADR 0043); removing or renaming a
// field is a breaking change requiring a new api_version. Read handlers call
// the relevant service (never a repository directly); write handlers call
// service methods that publish task.* events (never repository.TaskRepository).
type HostServer interface {
	GetState(context.Context, *GetStateRequest) (*GetStateResponse, error)
	SetState(context.Context, *SetStateRequest) (*SetStateResponse, error)
	DeleteState(context.Context, *DeleteStateRequest) (*DeleteStateResponse, error)
	ListState(context.Context, *ListStateRequest) (*ListStateResponse, error)
	RevealSecret(context.Context, *RevealSecretRequest) (*RevealSecretResponse, error)
	EmitEvent(context.Context, *EmitEventRequest) (*EmitEventResponse, error)
	// Plugin-scoped secret primitives — capability `secrets`, like
	// RevealSecret. Keys are namespaced server-side to the calling plugin
	// (vault id "plugin:<id>:secret:<key>"), so a plugin can only ever read,
	// write, or delete its OWN secrets; RevealSecret remains the way to
	// resolve an operator-provided reference to a shared/global secret.
	// Values are stored in kandev's encrypted secret vault (AES-256-GCM at
	// rest), never on the plugin record or config file.
	GetSecret(context.Context, *GetSecretRequest) (*GetSecretResponse, error)
	SetSecret(context.Context, *SetSecretRequest) (*SetSecretResponse, error)
	DeleteSecret(context.Context, *DeleteSecretRequest) (*DeleteSecretResponse, error)
	// GetConfig returns the plugin's own operator-editable config (the values
	// set in Settings > Plugins > <plugin> against the manifest's
	// config_schema). Ungated: a plugin can always read its own config, secret
	// values included — that is how e.g. an operator-configured PAT reaches
	// the plugin.
	GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error)
	// Reads — capability api_read:<resource>
	ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error)
	GetTask(context.Context, *GetTaskRequest) (*GetTaskResponse, error)
	ListWorkspaces(context.Context, *ListWorkspacesRequest) (*ListWorkspacesResponse, error)
	ListWorkflows(context.Context, *ListWorkflowsRequest) (*ListWorkflowsResponse, error)
	ListWorkflowSteps(context.Context, *ListWorkflowStepsRequest) (*ListWorkflowStepsResponse, error)
	ListAgentProfiles(context.Context, *ListAgentProfilesRequest) (*ListAgentProfilesResponse, error)
	ListExecutorProfiles(context.Context, *ListExecutorProfilesRequest) (*ListExecutorProfilesResponse, error)
	ListRepositories(context.Context, *ListRepositoriesRequest) (*ListRepositoriesResponse, error)
	// Sessions + code stats — capability api_read:sessions. Driven by a real
	// plugin (kandev-plugin-agent-stats) that otherwise read task_sessions,
	// task_session_commits, and task_session_git_snapshots straight from the
	// SQLite file. SessionCodeStats is a COMPUTED, stable DTO — deliberately
	// not the raw commit/snapshot rows, whose JSON schema churns.
	ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error)
	ListSessionCodeStats(context.Context, *ListSessionCodeStatsRequest) (*ListSessionCodeStatsResponse, error)
	// Conversation content — capability api_read:messages. Historical
	// user/agent message content for a session or task, filterable by a time
	// range (e.g. "yesterday"). Content is sanitized: kandev-injected
	// <kandev-system> blocks are stripped, exactly like the message.added bus
	// event — raw system prompts are never exposed to plugins.
	ListMessages(context.Context, *ListMessagesRequest) (*ListMessagesResponse, error)
	// Pending agent interactions — capability api_read:interactions. The
	// DURABLE record of every permission request and clarification bundle still
	// owed a human response, under the same turn/session authority kandev's own
	// list surfaces use. Session state alone cannot answer this: WAITING_FOR_INPUT
	// also describes an ordinarily completed turn, so a state-only consumer
	// reports attention that is not owed. Reading the record is what lets a
	// consumer that started late, restarted, or missed an event reconcile.
	// GetInteraction resolves ANY interaction — including terminal ones — so a
	// replayed or missed event converges on the current result instead of
	// NotFound.
	ListPendingInteractions(context.Context, *ListPendingInteractionsRequest) (*ListPendingInteractionsResponse, error)
	GetInteraction(context.Context, *GetInteractionRequest) (*GetInteractionResponse, error)
	// Utility agent — capability agent_invoke. Runs a one-shot, non-interactive
	// completion using the operator-configured "utility agent" profile (Settings
	// > System), so a plugin can delegate a lightweight LLM step without holding
	// its own API key. FailedPrecondition when no utility agent is configured.
	InvokeUtilityAgent(context.Context, *InvokeUtilityAgentRequest) (*InvokeUtilityAgentResponse, error)
	// Writes — capability api_write:<resource>. Route through the first-party
	// service layer so events fire and WS clients update — the whole reason not
	// to let plugins write the DB. CreateTask/UpdateTask require api_write:tasks
	// and go through the task service (task.* events; kandev stamps
	// source = "plugin:<id>" on created rows, a plugin cannot set it). SendMessage
	// requires api_write:messages and delivers a prompt to a task session through
	// the orchestrator — the same delivery path message_task uses (queue when the
	// session is running, resume/start it otherwise).
	CreateTask(context.Context, *CreateTaskRequest) (*CreateTaskResponse, error)
	UpdateTask(context.Context, *UpdateTaskRequest) (*UpdateTaskResponse, error)
	// MoveTask transitions a task to a workflow step through the same path the
	// board's own move uses (validation, WIP admission, task.moved publication,
	// auto-start gates, queue reconciliation) — unlike UpdateTask, which rejects
	// workflow_step_id. Requires api_write:tasks.
	MoveTask(context.Context, *MoveTaskRequest) (*MoveTaskResponse, error)
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error)
	PreviewPluginOwnedTaskTree(context.Context, *PreviewPluginOwnedTaskTreeRequest) (*PreviewPluginOwnedTaskTreeResponse, error)
	DeletePluginOwnedTaskTree(context.Context, *DeletePluginOwnedTaskTreeRequest) (*DeletePluginOwnedTaskTreeResponse, error)
	// Interaction responses — capability api_write:interactions. Each routes
	// through the same first-party service the native UI uses, so the agent
	// unblocks, the durable record turns terminal, and every surface converges
	// through the normal events. Terminal-once: an interaction that already has
	// a resolution answers FailedPrecondition rather than dispatching a second
	// response, and an unknown id answers NotFound — the two outcomes a
	// reconciling cache needs to distinguish "someone else got there first" from
	// "I am holding a stale id".
	RespondToPermission(context.Context, *RespondToPermissionRequest) (*RespondToPermissionResponse, error)
	AnswerClarification(context.Context, *AnswerClarificationRequest) (*AnswerClarificationResponse, error)
	CancelClarification(context.Context, *CancelClarificationRequest) (*CancelClarificationResponse, error)
	mustEmbedUnimplementedHostServer()
}

// UnimplementedHostServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHostServer struct{}

func (UnimplementedHostServer) GetState(context.Context, *GetStateRequest) (*GetStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetState not implemented")
}
func (UnimplementedHostServer) SetState(context.Context, *SetStateRequest) (*SetStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetState not implemented")
}
func (UnimplementedHostServer) DeleteState(context.Context, *DeleteStateRequest) (*DeleteStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteState not implemented")
}
func (UnimplementedHostServer) ListState(context.Context, *ListStateRequest) (*ListStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListState not implemented")
}
func (UnimplementedHostServer) RevealSecret(context.Context, *RevealSecretRequest) (*RevealSecretResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevealSecret not implemented")
}
func (UnimplementedHostServer) EmitEvent(context.Context, *EmitEventRequest) (*EmitEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EmitEvent not implemented")
}
func (UnimplementedHostServer) GetSecret(context.Context, *GetSecretRequest) (*GetSecretResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSecret not implemented")
}
func (UnimplementedHostServer) SetSecret(context.Context, *SetSecretRequest) (*SetSecretResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetSecret not implemented")
}
func (UnimplementedHostServer) DeleteSecret(context.Context, *DeleteSecretRequest) (*DeleteSecretResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSecret not implemented")
}
func (UnimplementedHostServer) GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedHostServer) ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTasks not implemented")
}
func (UnimplementedHostServer) GetTask(context.Context, *GetTaskRequest) (*GetTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTask not implemented")
}
func (UnimplementedHostServer) ListWorkspaces(context.Context, *ListWorkspacesRequest) (*ListWorkspacesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWorkspaces not implemented")
}
func (UnimplementedHostServer) ListWorkflows(context.Context, *ListWorkflowsRequest) (*ListWorkflowsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWorkflows not implemented")
}
func (UnimplementedHostServer) ListWorkflowSteps(context.Context, *ListWorkflowStepsRequest) (*ListWorkflowStepsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWorkflowSteps not implemented")
}
func (UnimplementedHostServer) ListAgentProfiles(context.Context, *ListAgentProfilesRequest) (*ListAgentProfilesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAgentProfiles not implemented")
}
func (UnimplementedHostServer) ListExecutorProfiles(context.Context, *ListExecutorProfilesRequest) (*ListExecutorProfilesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListExecutorProfiles not implemented")
}
func (UnimplementedHostServer) ListRepositories(context.Context, *ListRepositoriesRequest) (*ListRepositoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRepositories not implemented")
}
func (UnimplementedHostServer) ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedHostServer) ListSessionCodeStats(context.Context, *ListSessionCodeStatsRequest) (*ListSessionCodeStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSessionCodeStats not implemented")
}
func (UnimplementedHostServer) ListMessages(context.Context, *ListMessagesRequest) (*ListMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMessages not implemented")
}
func (UnimplementedHostServer) ListPendingInteractions(context.Context, *ListPendingInteractionsRequest) (*ListPendingInteractionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPendingInteractions not implemented")
}
func (UnimplementedHostServer) GetInteraction(context.Context, *GetInteractionRequest) (*GetInteractionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInteraction not implemented")
}
func (UnimplementedHostServer) InvokeUtilityAgent(context.Context, *InvokeUtilityAgentRequest) (*InvokeUtilityAgentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InvokeUtilityAgent not implemented")
}
func (UnimplementedHostServer) CreateTask(context.Context, *CreateTaskRequest) (*CreateTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTask not implemented")
}
func (UnimplementedHostServer) UpdateTask(context.Context, *UpdateTaskRequest) (*UpdateTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTask not implemented")
}
func (UnimplementedHostServer) MoveTask(context.Context, *MoveTaskRequest) (*MoveTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MoveTask not implemented")
}
func (UnimplementedHostServer) SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedHostServer) PreviewPluginOwnedTaskTree(context.Context, *PreviewPluginOwnedTaskTreeRequest) (*PreviewPluginOwnedTaskTreeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PreviewPluginOwnedTaskTree not implemented")
}
func (UnimplementedHostServer) DeletePluginOwnedTaskTree(context.Context, *DeletePluginOwnedTaskTreeRequest) (*DeletePluginOwnedTaskTreeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePluginOwnedTaskTree not implemented")
}
func (UnimplementedHostServer) RespondToPermission(context.Context, *RespondToPermissionRequest) (*RespondToPermissionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RespondToPermission not implemented")
}
func (UnimplementedHostServer) AnswerClarification(context.Context, *AnswerClarificationRequest) (*AnswerClarificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnswerClarification not implemented")
}
func (UnimplementedHostServer) CancelClarification(context.Context, *CancelClarificationRequest) (*CancelClarificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelClarification not implemented")
}
func (UnimplementedHostServer) mustEmbedUnimplementedHostServer() {}
func (UnimplementedHostServer) testEmbeddedByValue()              {}

// UnsafeHostServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HostServer will
// result in compilation errors.
type UnsafeHostServer interface {
	mustEmbedUnimplementedHostServer()
}

func RegisterHostServer(s grpc.ServiceRegistrar, srv HostServer) {
	// If the following call pancis, it indicates UnimplementedHostServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Host_ServiceDesc, srv)
}

func _Host_GetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_GetState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).GetState(ctx, req.(*GetStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_SetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).SetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_SetState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).SetState(ctx, req.(*SetStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_DeleteState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).DeleteState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_DeleteState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).DeleteState(ctx, req.(*DeleteStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_ListState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).ListState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_ListState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).ListState(ctx, req.(*ListStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_RevealSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevealSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).RevealSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_RevealSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).RevealSecret(ctx, req.(*RevealSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_EmitEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmitEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).EmitEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_EmitEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).EmitEvent(ctx, req.(*EmitEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_GetSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).GetSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_GetSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).GetSecret(ctx, req.(*GetSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_SetSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).SetSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_SetSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).SetSecret(ctx, req.(*SetSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_DeleteSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).DeleteSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_DeleteSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).DeleteSecret(ctx, req.(*DeleteSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_ListTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).ListTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_ListTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).ListTasks(ctx, req.(*ListTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_GetTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).GetTask(ctx, req.(*GetTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_ListWorkspaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkspacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).ListWorkspaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_ListWorkspaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).ListWorkspaces(ctx, req.(*ListWorkspacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_ListWorkflows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkflowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).ListWorkflows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_ListWorkflows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).ListWorkflows(ctx, req.(*ListWorkflowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_ListWorkflowSteps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkflowStepsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).ListWorkflowSteps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_ListWorkflowSteps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).ListWorkflowSteps(ctx, req.(*ListWorkflowStepsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_ListAgentProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentProfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).ListAgentProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_ListAgentProfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).ListAgentProfiles(ctx, req.(*ListAgentProfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_ListExecutorProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListExecutorProfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).ListExecutorProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_ListExecutorProfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).ListExecutorProfiles(ctx, req.(*ListExecutorProfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_ListRepositories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRepositoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).ListRepositories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_ListRepositories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).ListRepositories(ctx, req.(*ListRepositoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).ListSessions(ctx, req.(*ListSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_ListSessionCodeStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionCodeStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).ListSessionCodeStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_ListSessionCodeStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).ListSessionCodeStats(ctx, req.(*ListSessionCodeStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_ListMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).ListMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_ListMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).ListMessages(ctx, req.(*ListMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_ListPendingInteractions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPendingInteractionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).ListPendingInteractions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_ListPendingInteractions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).ListPendingInteractions(ctx, req.(*ListPendingInteractionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_GetInteraction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInteractionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).GetInteraction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_GetInteraction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).GetInteraction(ctx, req.(*GetInteractionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_InvokeUtilityAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeUtilityAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).InvokeUtilityAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_InvokeUtilityAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).InvokeUtilityAgent(ctx, req.(*InvokeUtilityAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_CreateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).CreateTask(ctx, req.(*CreateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_UpdateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).UpdateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_UpdateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).UpdateTask(ctx, req.(*UpdateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_MoveTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).MoveTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_MoveTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).MoveTask(ctx, req.(*MoveTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_PreviewPluginOwnedTaskTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreviewPluginOwnedTaskTreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).PreviewPluginOwnedTaskTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_PreviewPluginOwnedTaskTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).PreviewPluginOwnedTaskTree(ctx, req.(*PreviewPluginOwnedTaskTreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_DeletePluginOwnedTaskTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePluginOwnedTaskTreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).DeletePluginOwnedTaskTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_DeletePluginOwnedTaskTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).DeletePluginOwnedTaskTree(ctx, req.(*DeletePluginOwnedTaskTreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_RespondToPermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RespondToPermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).RespondToPermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_RespondToPermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).RespondToPermission(ctx, req.(*RespondToPermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_AnswerClarification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnswerClarificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).AnswerClarification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_AnswerClarification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).AnswerClarification(ctx, req.(*AnswerClarificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_CancelClarification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelClarificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).CancelClarification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_CancelClarification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).CancelClarification(ctx, req.(*CancelClarificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Host_ServiceDesc is the grpc.ServiceDesc for Host service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Host_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kandev.plugin.v1.Host",
	HandlerType: (*HostServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetState",
			Handler:    _Host_GetState_Handler,
		},
		{
			MethodName: "SetState",
			Handler:    _Host_SetState_Handler,
		},
		{
			MethodName: "DeleteState",
			Handler:    _Host_DeleteState_Handler,
		},
		{
			MethodName: "ListState",
			Handler:    _Host_ListState_Handler,
		},
		{
			MethodName: "RevealSecret",
			Handler:    _Host_RevealSecret_Handler,
		},
		{
			MethodName: "EmitEvent",
			Handler:    _Host_EmitEvent_Handler,
		},
		{
			MethodName: "GetSecret",
			Handler:    _Host_GetSecret_Handler,
		},
		{
			MethodName: "SetSecret",
			Handler:    _Host_SetSecret_Handler,
		},
		{
			MethodName: "DeleteSecret",
			Handler:    _Host_DeleteSecret_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _Host_GetConfig_Handler,
		},
		{
			MethodName: "ListTasks",
			Handler:    _Host_ListTasks_Handler,
		},
		{
			MethodName: "GetTask",
			Handler:    _Host_GetTask_Handler,
		},
		{
			MethodName: "ListWorkspaces",
			Handler:    _Host_ListWorkspaces_Handler,
		},
		{
			MethodName: "ListWorkflows",
			Handler:    _Host_ListWorkflows_Handler,
		},
		{
			MethodName: "ListWorkflowSteps",
			Handler:    _Host_ListWorkflowSteps_Handler,
		},
		{
			MethodName: "ListAgentProfiles",
			Handler:    _Host_ListAgentProfiles_Handler,
		},
		{
			MethodName: "ListExecutorProfiles",
			Handler:    _Host_ListExecutorProfiles_Handler,
		},
		{
			MethodName: "ListRepositories",
			Handler:    _Host_ListRepositories_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _Host_ListSessions_Handler,
		},
		{
			MethodName: "ListSessionCodeStats",
			Handler:    _Host_ListSessionCodeStats_Handler,
		},
		{
			MethodName: "ListMessages",
			Handler:    _Host_ListMessages_Handler,
		},
		{
			MethodName: "ListPendingInteractions",
			Handler:    _Host_ListPendingInteractions_Handler,
		},
		{
			MethodName: "GetInteraction",
			Handler:    _Host_GetInteraction_Handler,
		},
		{
			MethodName: "InvokeUtilityAgent",
			Handler:    _Host_InvokeUtilityAgent_Handler,
		},
		{
			MethodName: "CreateTask",
			Handler:    _Host_CreateTask_Handler,
		},
		{
			MethodName: "UpdateTask",
			Handler:    _Host_UpdateTask_Handler,
		},
		{
			MethodName: "MoveTask",
			Handler:    _Host_MoveTask_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _Host_SendMessage_Handler,
		},
		{
			MethodName: "PreviewPluginOwnedTaskTree",
			Handler:    _Host_PreviewPluginOwnedTaskTree_Handler,
		},
		{
			MethodName: "DeletePluginOwnedTaskTree",
			Handler:    _Host_DeletePluginOwnedTaskTree_Handler,
		},
		{
			MethodName: "RespondToPermission",
			Handler:    _Host_RespondToPermission_Handler,
		},
		{
			MethodName: "AnswerClarification",
			Handler:    _Host_AnswerClarification_Handler,
		},
		{
			MethodName: "CancelClarification",
			Handler:    _Host_CancelClarification_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kandev/plugin/v1/plugin.proto",
}
