#!/usr/bin/env bash
# deploy-user-service.test.sh — isolate publish/install against a fake HOME.
# @covers AC-LAUNCHER-SOURCE-DEPLOY-001.1
# @covers AC-LAUNCHER-SOURCE-DEPLOY-001.3
# @covers AC-LAUNCHER-SOURCE-DEPLOY-001.4
# @covers AC-LAUNCHER-SOURCE-DEPLOY-001.5
# @covers AC-LAUNCHER-SOURCE-DEPLOY-001.7
# @covers AC-LAUNCHER-SOURCE-DEPLOY-002.1
# @covers AC-LAUNCHER-SOURCE-DEPLOY-002.2
# @covers AC-LAUNCHER-SOURCE-DEPLOY-002.4
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCRIPT="$ROOT_DIR/scripts/deploy-user-service.sh"
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

status=0

pass() {
	printf 'ok    %s\n' "$1"
}

fail() {
	printf 'FAIL  %s\n' "$1" >&2
	status=1
}

write_fake_kandev() {
	local path="$1"
	cat >"$path" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
{
	printf 'argv:'
	printf ' %q' "$0" "$@"
	printf '\n'
} >>"${KANDEV_ARGV_LOG:?}"
EOF
	chmod +x "$path"
}

make_complete_bundle() {
	local bundle_dir="$1"
	mkdir -p "$bundle_dir/bin"
	write_fake_kandev "$bundle_dir/bin/kandev"
	touch \
		"$bundle_dir/bin/agentctl" \
		"$bundle_dir/bin/agentctl-linux-amd64" \
		"$bundle_dir/bin/agentctl-linux-arm64" \
		"$bundle_dir/bin/agentctl-darwin-arm64" \
		"$bundle_dir/bin/agentctl-darwin-amd64"
	chmod +x "$bundle_dir/bin/"*
}

write_managed_unit() {
	local unit_path="$1" home_dir="$2" port="${3:-}"
	mkdir -p "$(dirname "$unit_path")"
	{
		printf '%s\n' '# managed by kandev — regenerated by `kandev service install`'
		printf '%s\n' '[Service]'
		printf 'Environment=KANDEV_HOME_DIR=%s\n' "$home_dir"
		if [ -n "$port" ]; then
			printf 'Environment=KANDEV_SERVER_PORT=%s\n' "$port"
		fi
	} >"$unit_path"
}

new_home() {
	local dir
	dir="$(mktemp -d "$TMP_DIR/home.XXXXXX")"
	mkdir -p "$dir/.config/systemd/user"
	printf '%s\n' "$dir"
}

run_deploy() {
	local home="$1"
	shift
	env -u HOME_DIR -u PORT -u NO_BOOT_START \
		HOME="$home" \
		KANDEV_ARGV_LOG="$home/argv.log" \
		XDG_CONFIG_HOME="$home/.config" \
		"$SCRIPT" "$@"
}

# --- missing unit installs into $HOME/.kandev and never passes --system ---
home="$(new_home)"
checkout="$TMP_DIR/checkout"
mkdir -p "$checkout"
bundle="$home/staging"
make_complete_bundle "$bundle"
: >"$home/argv.log"
if ! out="$(run_deploy "$home" --bundle-dir "$bundle" --checkout "$checkout" 2>"$home/err")"; then
	fail "default home install: $(cat "$home/err")"
else
	published="$home/.kandev/runtime/bin/kandev"
	if [ -x "$published" ]; then
		pass "default home publishes to \$HOME/.kandev/runtime"
	else
		fail "default home publishes to \$HOME/.kandev/runtime"
	fi
	if grep -q 'service install' "$home/argv.log" && ! grep -q -- '--system' "$home/argv.log"; then
		pass "install is user-domain (no --system)"
	else
		fail "install is user-domain (no --system): $(cat "$home/argv.log")"
	fi
	if grep -q -- "--home-dir $home/.kandev" "$home/argv.log" || grep -q -- "--home-dir=$home/.kandev" "$home/argv.log"; then
		pass "default install passes --home-dir \$HOME/.kandev"
	else
		fail "default install passes --home-dir \$HOME/.kandev: $(cat "$home/argv.log")"
	fi
	if grep -q 'service restart' "$home/argv.log"; then
		pass "install is followed by service restart"
	else
		fail "install is followed by service restart: $(cat "$home/argv.log")"
	fi
	if printf '%s\n' "$out" | grep -Fq "$published" && printf '%s\n' "$out" | grep -Fq "$home/.kandev" && printf '%s\n' "$out" | grep -Eiq 'user-domain|user systemd|user service'; then
		pass "success output names executable, home, and user-domain"
	else
		fail "success output names executable, home, and user-domain: $out"
	fi
	if ! grep -q 'KANDEV_WEB_DIST_DIR' "$home/argv.log"; then
		pass "install argv omits KANDEV_WEB_DIST_DIR"
	else
		fail "install argv omits KANDEV_WEB_DIST_DIR"
	fi
fi

# --- existing managed unit home/port are reused ---
home="$(new_home)"
checkout="$TMP_DIR/checkout-2"
mkdir -p "$checkout"
live_home="$home/live-kandev"
mkdir -p "$live_home"
write_managed_unit "$home/.config/systemd/user/kandev.service" "$live_home" "40131"
bundle="$home/staging"
make_complete_bundle "$bundle"
: >"$home/argv.log"
if ! run_deploy "$home" --bundle-dir "$bundle" --checkout "$checkout" >/dev/null 2>"$home/err"; then
	fail "existing unit reuse: $(cat "$home/err")"
else
	if [ -x "$live_home/runtime/bin/kandev" ]; then
		pass "existing unit publishes under recorded home"
	else
		fail "existing unit publishes under recorded home"
	fi
	if grep -E -q -- "--home-dir(=| )$live_home( |$)" "$home/argv.log"; then
		pass "existing unit passes recorded --home-dir"
	else
		fail "existing unit passes recorded --home-dir: $(cat "$home/argv.log")"
	fi
	if grep -E -q -- "--port(=| )40131( |$)" "$home/argv.log"; then
		pass "existing unit passes recorded --port"
	else
		fail "existing unit passes recorded --port: $(cat "$home/argv.log")"
	fi
fi

# --- HOME_DIR and PORT overrides beat the unit ---
home="$(new_home)"
checkout="$TMP_DIR/checkout-3"
mkdir -p "$checkout"
write_managed_unit "$home/.config/systemd/user/kandev.service" "$home/old-home" "1111"
override_home="$home/new-home"
mkdir -p "$override_home"
bundle="$home/staging"
make_complete_bundle "$bundle"
: >"$home/argv.log"
if ! run_deploy "$home" --bundle-dir "$bundle" --checkout "$checkout" --home-dir "$override_home" --port 2222 >/dev/null 2>"$home/err"; then
	fail "HOME_DIR/PORT override: $(cat "$home/err")"
else
	if [ -x "$override_home/runtime/bin/kandev" ]; then
		pass "HOME_DIR override publishes to the new home"
	else
		fail "HOME_DIR override publishes to the new home"
	fi
	if grep -E -q -- "--home-dir(=| )$override_home( |$)" "$home/argv.log" && grep -E -q -- "--port(=| )2222( |$)" "$home/argv.log"; then
		pass "explicit HOME_DIR and PORT win over the unit"
	else
		fail "explicit HOME_DIR and PORT win over the unit: $(cat "$home/argv.log")"
	fi
fi

# --- incomplete bundle does not replace a previous runtime ---
home="$(new_home)"
checkout="$TMP_DIR/checkout-4"
mkdir -p "$checkout"
live_home="$home/.kandev"
mkdir -p "$live_home/runtime/bin"
printf 'OLD\n' >"$live_home/runtime/bin/kandev"
chmod +x "$live_home/runtime/bin/kandev"
bundle="$home/staging"
make_complete_bundle "$bundle"
rm "$bundle/bin/agentctl-linux-arm64"
if run_deploy "$home" --bundle-dir "$bundle" --checkout "$checkout" >/dev/null 2>"$home/err"; then
	fail "incomplete bundle should exit non-zero"
else
	if grep -q 'OLD' "$live_home/runtime/bin/kandev" && grep -q 'agentctl-linux-arm64' "$home/err"; then
		pass "incomplete bundle leaves previous runtime in place"
	else
		fail "incomplete bundle leaves previous runtime in place: $(cat "$home/err")"
	fi
fi

# --- refuse checkout as live home ---
home="$(new_home)"
checkout="$TMP_DIR/checkout-src"
mkdir -p "$checkout"
bundle="$home/staging"
make_complete_bundle "$bundle"
if run_deploy "$home" --bundle-dir "$bundle" --checkout "$checkout" --home-dir "$checkout" >/dev/null 2>"$home/err"; then
	fail "checkout home should be refused"
else
	if grep -qi 'checkout' "$home/err"; then
		pass "checkout home is refused"
	else
		fail "checkout home is refused: $(cat "$home/err")"
	fi
fi

# --- refuse .kandev-dev as live home ---
home="$(new_home)"
checkout="$TMP_DIR/checkout-dev"
mkdir -p "$checkout"
dev_home="$home/repo/.kandev-dev"
mkdir -p "$dev_home"
bundle="$home/staging"
make_complete_bundle "$bundle"
if run_deploy "$home" --bundle-dir "$bundle" --checkout "$checkout" --home-dir "$dev_home" >/dev/null 2>"$home/err"; then
	fail ".kandev-dev home should be refused"
else
	if grep -q '.kandev-dev' "$home/err"; then
		pass ".kandev-dev home is refused"
	else
		fail ".kandev-dev home is refused: $(cat "$home/err")"
	fi
fi

# --- a task worktree checkout still publishes to the live home ---
home="$(new_home)"
checkout="$home/.kandev/tasks/make-deploy-example/kandev"
mkdir -p "$checkout"
bundle="$home/staging"
make_complete_bundle "$bundle"
: >"$home/argv.log"
if ! run_deploy "$home" --bundle-dir "$bundle" --checkout "$checkout" >/dev/null 2>"$home/err"; then
	fail "task worktree checkout: $(cat "$home/err")"
else
	if [ -x "$home/.kandev/runtime/bin/kandev" ] && [ ! -e "$checkout/runtime/bin/kandev" ]; then
		pass "task worktree publishes to live home, not the worktree"
	else
		fail "task worktree publishes to live home, not the worktree"
	fi
fi

if [ "$status" -eq 0 ]; then
	echo "All deploy-user-service checks passed."
fi
exit "$status"
